### PR TITLE
Browser tests

### PR DESCRIPTION
**Pull request by diasdavid**
~~WIP~~

### CODE REVIEW

**Comment by diasdavid** [comment]
Trying to understand what dark magic is this where browser tests pass and `Buffer` is available in the browser without any hack

**Comment by diasdavid** [comment]
it is all good :) ready for merge and publish! :)

**Comment by jbenet** [comment]
LGTM thanks @diasdavid

**Comment by jbenet** [comment]
@diasdavid bump patch or minor?

**Comment by diasdavid** [comment]
the interface didn't change, but now we officially support it running on the browser and explain how, so I would say bump minor :)

**Comment by harlantwood** [comment]
Excellent work :)

**Comment by diasdavid** [comment]
Thank you @harlantwood :)

**Pull request merged**
